#!/usr/bin/env python

import sys

_contacts = [line.strip() for line in open(".contacts", 'r')]

contacts = {}
for c in range(len(_contacts)):
    con = _contacts[c].split()
    contacts[con[0]] = con[1]

def add_contact(name, number):
    with open('.contacts', 'a') as file:
        file.write(name + "\t" + number + "\n")
        contacts[name] = number

def get_number(name):
    if name in contacts:
        return contacts[name]
    return False


def list_contacts(prefix=""):
    return [i for i in contacts.keys() if prefix in i]

def main(argv):
    command = argv[0]
    if command in ['add', 'a', 'create']:
        add_contact(argv[1], argv[2])
    elif command in ['list', 'ls', 'l']:
        print '\t'.join(list_contacts(argv[1] if len(argv) >1 else ''))

if __name__ == "__main__":
    main(sys.argv[1:])
